# Quests config
#
#
# allow-command-questing: true/false
#    Should we allow players to take Quests via commands?
#
# allow-command-quests-with-npcs: true/false
#    Should we allow players to take Quests via commands, that have NPCs as quest starters?
#
# show-requirements: true/false
#    Should players be told the exact requirements of a Quest when they look at its info (via command)?
#
# allow-quitting: true/false
#    Should players be allowed to quit a Quest after they've taken it?
#
# debug-mode: true/false
#    Should debugging information be printed out to console?
#
# kill-time: number
#    How long (in seconds) should a player have to wait before they can kill the same player for a Quest?
allow-command-questing: true
allow-command-quests-with-npcs: false
show-requirements: true
allow-quitting: true
debug-mode: false
kill-delay: 600
quester-blacklist:
  - "SomeGuy12345"
  - "somePrefix*"
  - "*someSuffix"
  - "*someRegex*"



